### ISSUE TITLE
Discovery no longer works with JMDNS

### ISSUE THREAD

**Issue by erullmann** [aurae/RxBonjour#12]
Recently (in the past two days or so) service discovery with JMDNS has stopped working. It was working last week. It works with NSDManager but then I can't get the txt records that I need. Going back to previous versions doesn't work, as does going back to previous versions of my code. If I open up a different app that does service discovery, like https://play.google.com/store/apps/details?id=com.druk.bonjour.browser&hl=en and then go back to my app it will find some services. Do you know anything that could be causing this issue? I am using a Moto X 2nd gen with Android 6.0.

Many thanks.

**Comment by mannodermaus** [comment]
Huh, that is really odd. Off the top of my head, I don't have any immediate ideas as to why you're experiencing this issue. It's weird that it stopped working only recently. Do you pull in JmDNS using a different, potentially dynamic dependency alongside RxBonjour, and a recent update of theirs broke support with this lib? Then again, that wouldn't explain why it starts working again after resuming from another app.
