### ISSUE TITLE
Update JmDNS dependency

### ISSUE THREAD

**Issue by mannodermaus** [aurae/RxBonjour#15]
Last I checked, the guys over at JmDNS are at version 3.5.1 right now, whereas RxBonjour still pulls in an older version.

**Comment by mannodermaus** [comment]
Note: This has already happened on develop, but the new artifacts still haven't been linked to JCenter. I have reached out to Bintray support again about this.

**Comment by delkant** [comment]
Hi!
Can this be why after I upgraded my project to gradle 3.3 it is failing to resolve RxBoujour?

**Comment by mannodermaus** [comment]
No, this should be unrelated. How are you pulling in the dependency? Does it work when you go back to an older version of Gradle?

**Comment by delkant** [comment]
I am sorry for the delay. Yes, it works when I go back to an older version. I was using it for a long time(8months, a few gradle upgrades). After I updated to the latest version suggested by Android Studio, my app won't build if I am including RxBonjour 

I am pulling in the dependency like this:
```

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'
    defaultConfig {
        applicationId "com.myapp"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 110
        versionName "1.1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
    lintOptions{
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:appcompat-v7:25.1.1'
    compile 'com.android.support:recyclerview-v7:25.1.1'
    compile 'com.android.support:cardview-v7:25.1.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha4'
    compile 'com.android.support:design:25.1.1'
    
   /*more dependencies here*/ 

   //compile 'com.github.aurae:rxbonjour:0.4.0'
    
    testCompile 'junit:junit:4.12'
}
```

**Comment by aaronvargas** [comment]
Yes, please update the Dependency and bump the version number. 0.4.0 uses a jmdns version that has a bug results in services not being reported as resolved! See ListenerStatus. _sameInfo() - bug is that the address is not compared and so is reported as same! Just spent a ton of time tracking this down only to find out it's been fixed for a long time... :(

For now we can use jitpack with
    compile ("com.github.aurae:rxbonjour:9e822d4b5e")
    compile ("org.jmdns:jmdns:3.5.1")

**Comment by mannodermaus** [comment]
I have dedicated some resources to get the dormant developments on the library up and running. It's going to take a bit for the new artifacts to be synchronized to jcenter, but after that's done, you'll be able to migrate to the new version using these coordinates:

```groovy
api "de.mannodermaus.rxjava:rxbonjour:1.0.0" // For RxJava 1
api "de.mannodermaus.rxjava2:rxbonjour:2.0.0-beta1" // For RxJava 2
```
Migration is simply a matter of renaming packages & making sure you apply `Schedulers` yourself, since the library won't anymore. ~~If you can't wait for jcenter, add this repo to your build script to pull it from Bintray directly:~~ **edit:** No need anymore, jcenter is synchronized now

```groovy
repositories {
    maven { url "https://dl.bintray.com/aurae/maven" }
}
```

Sorry this took so long!
