### ISSUE TITLE
Split into RxBonjour core and RxBonjour Android

### ISSUE THREAD

**Issue by tntclaus** [aurae/RxBonjour#17]
I am developing a set of applications which are intended to run on Desktop and Android devices. RxBonjour is good (because it is rx ^_^ ), but as far as I understand it can't be a dependency to pure java app because of its' android nature and android dependencies. 

What are your thoughts about it?

**Comment by mannodermaus** [comment]
At this time, RxBonjour is only usable in Android projects, correct. After a quick examination of the project, the Android `Context` is only used to look-up the `NsdManager` and `WifiManager`, respectively. I'm intrigued by the idea of extending this library's scope, and I'll take it into account for the current development cycle (which also involves opening up to RxJava 2.x, so the changelog's already pretty involved)!

**Comment by mannodermaus** [comment]
I have just released the first Release Candidate of RxBonjour 2, which introduces cross-platform support using multiple dependencies. Unlike previous versions including the 2.x beta releases, you need to include multiple artifacts that power your RxBonjour instance. Please check the README for more details.

Going forward with supporting Desktop-based projects, my question would be what kind of additions you would like to see in regards to the library. Right now, all Android-related code is moved outside the core library and into `rxbonjour-platform-android`, rendering the Desktop-based Platform pretty much empty right now. Depending on what you would need on top of that, this could be extended accordingly. Please let me know!
