### ISSUE TITLE
Please add proguard rules to README

### ISSUE THREAD

**Issue by aaronvargas** [aurae/RxBonjour#20]
Can you add the proguard rules needed to use this library. Helps out people getting started! 
Thanks!!

**Comment by mannodermaus** [comment]
RxBonjour doesn't require any ProGuard Keep statements because it doesn't rely on reflective API access. Are you experiencing issues and/or crashes with the library and ProGuard activated? If so, could you share the exception message?

**Comment by mannodermaus** [comment]
Please feel free to re-open if you have any more information to share regarding missing ProGuard rules, e.g. a stacktrace of a missing class at runtime related to RxBonjour.

**Comment by aaronvargas** [comment]
The 1.x version relies on RxJava 1.x so I needed the rules in https://github.com/artem-zinnatullin/RxJavaProGuardRules
Looks like 2.x doesn't need it, but haven't tried.

**Comment by mannodermaus** [comment]
I wasn't aware that RxJava 1 doesn't bundle its Proguard rules, since I haven't used that one for a while. Probably reasonable to either refer users to that repository you linked, or bundle the rules directly.

**Comment by mannodermaus** [comment]
I've added a notice to the 1.x README about this.
