### ISSUE TITLE
Expose DNS-SD TXT records in BonjourService

### ISSUE THREAD

**Issue by curioustechizen** [aurae/RxBonjour#3]
JmDNS already provides this info via ServiceInfo#getPropertyNames and ServiceInfo#getProprtyString(String) methods. 

NsdManager only has [`getAttributes`](https://developer.android.com/reference/android/net/nsd/NsdServiceInfo.html#getAttributes%28%29) from API 21 onwards, so you could consider returning an empty collection if user chooses to use the NsdManager API and running on API level < 21.

**Comment by mannodermaus** [comment]
This would be a nice addition. I suppose constructing a `Bundle` containing the key-value pairs would be the way to go.

**Comment by curioustechizen** [comment]
Actually, even on API 21 this still doesn't really work :( so only if you use JmDNS do you get the expected behavior  - https://code.google.com/p/android/issues/detail?id=136099

**Comment by mannodermaus** [comment]
I can't say that I'm surprised, to be honest. :D Still, I will prepare the data to include TXT records.

**Comment by mannodermaus** [comment]
This is implemented now and will be included in version 0.1.5 of the library.
